name: Auto Close Issues

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  close-issues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    
    steps:
      - name: Close issues from PR body
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body || '';
            const commitMsg = context.payload.pull_request.merge_commit_message || '';
            const text = `${prBody}\n${commitMsg}`;
            
            // close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved 키워드로 이슈 번호 찾기
            const issueRegex = /(?:close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)\s+#(\d+)/gi;
            const matches = [...text.matchAll(issueRegex)];
            const issueNumbers = [...new Set(matches.map(m => parseInt(m[1])))];
            
            if (issueNumbers.length === 0) {
              console.log('No issues found to close');
              return;
            }
            
            console.log(`Found issues to close: ${issueNumbers.join(', ')}`);
            
            for (const issueNumber of issueNumbers) {
              try {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  state: 'closed'
                });
                console.log(`Closed issue #${issueNumber}`);
              } catch (error) {
                console.log(`Failed to close issue #${issueNumber}: ${error.message}`);
              }
            }

