name: "ðŸ“¦ Chore(ìž¡ë¬´)"
description: "í™˜ê²½ì„¤ì • / ë¹Œë“œ / ì¸í”„ë¼ / CI/CD ë“± ê¸°íƒ€ ìž‘ì—…"
title: "[BE/chore] ì´ìŠˆ ì œëª©"
labels: ["chore"]

body:
  - type: textarea
    id: description
    attributes:
      label: ë‚´ìš©(Description)
      description: ì–´ë–¤ ìž‘ì—…ì¸ì§€ êµ¬ì²´ì ìœ¼ë¡œ ìž‘ì„±
      placeholder: >
        - ì˜ˆ: Gradle ì„¤ì • ë³€ê²½, CI/CD ìˆ˜ì •
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: ìž‘ì—… ë²”ìœ„(Scope)
      placeholder: |
        - [ ] ìž‘ì—… 1
        - [ ] ìž‘ì—… 2
    validations:
      required: true