name: "ðŸ“ Docs"
description: "ë¬¸ì„œ ìž‘ì—… ê´€ë ¨ Issue"
title: "[BE/docs] ì´ìŠˆ ì œëª©"
labels: ["docs"]

body:
  - type: textarea
    id: content
    attributes:
      label: ë¬¸ì„œ ë‚´ìš©
      description: ì–´ë–¤ ë¬¸ì„œë¥¼ ìž‘ì„±/ìˆ˜ì •í•´ì•¼ í•˜ëŠ”ì§€
      placeholder: >
        - API ë¬¸ì„œ
        - ERD
        - README
        - Flow ë¬¸ì„œ
    validations:
      required: true