name: "✨ Feature"
description: "새로운 기능을 추가하는 이슈"
title: "[BE/feat] 이슈 제목"
labels: ["feature"]

body:
  - type: textarea
    id: background
    attributes:
      label: 이슈 배경(Background)
      description: 왜 이 기능이 필요한지, 문제 상황/제약/방향성 작성
      placeholder: >
        - 어떤 문제가 있는지
        - 왜 기능이 필요한지
        - 어떤 방향이 맞는지
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: 작업 범위(Scope)
      description: 이 이슈에서 어디까지 작업할지 체크리스트 형태로 작성
      placeholder: |
        - [ ] 작업 1
        - [ ] 작업 2
    validations:
      required: true