name: "🐛 Fix"
description: "버그 / 오류 수정 이슈"
title: "[BE/fix] 이슈 제목"
labels: ["fix"]

body:
  - type: textarea
    id: bug-desc
    attributes:
      label: 문제 상황(Bug Description)
      description: 어떤 문제가 발생했는지 상세히 작성
      placeholder: >
        - 실제 동작:
        - 기대 동작:
        - 재현 방법:
    validations:
      required: true

  - type: textarea
    id: cause
    attributes:
      label: 해결법
      placeholder: >
        - 코드상 문제 지점:
        - 해결 방법: